//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let entitlements = entitlements()

  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 10 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// Value: Dogs
      ///
      /// Key: Dogs
      var dogs: RswiftResources.StringResource { .init(key: "Dogs", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Energy: %d/5
      ///
      /// Key: Energy
      var energy: RswiftResources.StringResource1<Int> { .init(key: "Energy", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Good With Strangers: %d/5
      ///
      /// Key: Good With Strangers
      var goodWithStrangers: RswiftResources.StringResource1<Int> { .init(key: "Good With Strangers", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: List
      ///
      /// Key: List
      var list: RswiftResources.StringResource { .init(key: "List", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Max Life Expectancy: %d years
      ///
      /// Key: Max Life Expectancy
      var maxLifeExpectancy: RswiftResources.StringResource1<Int> { .init(key: "Max Life Expectancy", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Min Life Expectancy: %d years
      ///
      /// Key: Min Life Expectancy
      var minLifeExpectancy: RswiftResources.StringResource1<Int> { .init(key: "Min Life Expectancy", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: No available list
      ///
      /// Key: No available list
      var noAvailableList: RswiftResources.StringResource { .init(key: "No available list", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Playfulness: %d/5
      ///
      /// Key: Playfulness
      var playfulness: RswiftResources.StringResource1<Int> { .init(key: "Playfulness", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Protectiveness: %d/5
      ///
      /// Key: Protectiveness
      var protectiveness: RswiftResources.StringResource1<Int> { .init(key: "Protectiveness", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Trainability: %d/5
      ///
      /// Key: Trainability
      var trainability: RswiftResources.StringResource1<Int> { .init(key: "Trainability", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 0 properties.
  struct entitlements {
    let comAppleSecurityAppSandbox: Bool = true
    let comAppleSecurityFilesUserSelectedReadOnly: Bool = true
  }
}